"""Bins Attributes

Revision ID: 42f75b2fc8b8
Revises: ef30836f32f4
Create Date: 2023-08-02 14:19:49.032140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42f75b2fc8b8'
down_revision = 'ef30836f32f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('width', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('depth', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('level', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('released', sa.Boolean(), nullable=True))
        batch_op.drop_column('slug')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('released')
        batch_op.drop_column('available')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('level')
        batch_op.drop_column('depth')
        batch_op.drop_column('width')
        batch_op.drop_column('height')

    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('date_posted', mysql.DATETIME(), nullable=True),
    sa.Column('slug', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('poster_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name='posts_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
