"""Initial Migration

Revision ID: 619e6a90aa4a
Revises: 
Create Date: 2023-07-23 20:43:50.598415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619e6a90aa4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
